### ISSUE TITLE
[Upstream]: BTCPS v1.6.10

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/service-pipeline#56]

**Comment by elvece** [comment]
Updated title to reflect latest available (1.6.7)

**Comment by elvece** [comment]
- [ ] https://github.com/Start9Labs/btcpayserver-wrapper/pull/30

**Comment by elvece** [comment]
In progress: refactor to use s6 init system for multiple processes in Docker container - this currently in testing / bugfixing

**Comment by elvece** [comment]
Cases tested for migration to using JS scripts for migrations, plus fixing prod for compatible versions (errors before due to incorrect pattern description key and regex for pattern description - didn't fail on prior released versions due to an eOS bug, which was resolved in a patch release)

1.6.6 installed, configured, started - downgrade to 1.4.7.3, no need to configure = success
1.6.6 installed, configured, started - downgrade to 1.4.7.4, no need to configure = success
1.6.6 installed, configured, started - downgrade to 1.4.7.1, no need to configure = success
1.6.6 installed, configured w/ bitcoin core, started - downgrade to 1.1.2.5, no need to configure, bitcoin core config moves to internal = s
1.6.6 installed, configured w/ proxy, started - downgrade to 1.1.2.5, no need to configure, proxy config moves to internal = s

1.1.2.5 installed, configured, with internal - upgrade to 1.6.6, needs config for sync start height, bitcoind rpc should now be internal-proxy = success
1.1.2.5 installed, configured, with external - upgrade to 1.6.6, needs config for sync start height, bitcoind rpc should now be internal-proxy = success
1.4.7.1 installed, configured, started - upgrade to 1.6.6,  no need to configure = success
1.4.7.3 installed, configured, started - upgrade to 1.6.6, no need to configure = success
1.4.7.3 installed, configured, started - upgrade to 1.6.6, no need to configure = success
